TEST add PrintModifiedFiles

diff --git a/.github/workflows/pr_push.yml b/.github/workflows/pr_push.yml
--- a/.github/workflows/pr_push.yml
+++ b/.github/workflows/pr_push.yml
@@ -20,58 +20,59 @@ jobs:
     uses: ./.github/workflows/reusable_checks.yml
   DocsBuild:
     uses: ./.github/workflows/reusable_docs_build.yml
+
   PrintModifiedFiles:
-    uses: ./.github/workflows/print_modified_files.yml
+    runs-on: ubuntu-latest
+    outputs:
+      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        with:
+          fetch-depth: 0
 
-  # PrintModifiedFiles:
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-  #       with:
-  #         fetch-depth: 0
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v45.0.3
 
-  #     - name: Get changed files
-  #       id: changed-files
-  #       uses: tj-actions/changed-files@v45.0.3
-
-  #     - name: List all changed files
-  #       env:
-  #         ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-  #       run: |
-  #         echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
+      - name: List all changed files
+        env:
+          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
 
   BuildCIContainer:
-    if: ${{ contains(needs.PrintModifiedFiles.outputs.changed_files, '.github/docker/') }}
+    if: ${{ contains(join(needs.PrintModifiedFiles.outputs.changed_files, ' '), '.github/docker/') }}
     needs: [PrintModifiedFiles]
     secrets: inherit
     uses: ./.github/workflows/build_ci_container.yml
-
   CheckStatus:
-      runs-on: ubuntu-latest
-      outputs:
-        check_status: ${{ steps.check_statuses.outputs.found }}
-      name: Check Status
-      needs: [CodeChecks, DocsBuild, BuildCIContainer]
-      if: always()
-      steps:
-      - uses: lwhiteley/dependent-jobs-result-check@v1
-        id: check_statuses
-        with:
-          statuses: failure
-          dependencies: ${{toJSON(needs) }}
-      - name: Log output
-        run: |
-          echo "statuses:" "${{ steps.check_statuses.outputs.statuses }}"
-          echo "jobs:" "${{ steps.check_statuses.outputs.jobs }}"
-          echo "found any?:" "${{ steps.check_statuses.outputs.found }}"
+    needs: [CodeChecks, DocsBuild, BuildCIContainer]
+    if: always()
+    uses: ./.github/workflows/check_status.yml
+  # CheckStatus:
+  #     runs-on: ubuntu-latest
+  #     outputs:
+  #       check_status: ${{ steps.check_statuses.outputs.found }}
+  #     name: Check Status
+  #     needs: [CodeChecks, DocsBuild, BuildCIContainer]
+  #     if: always()
+  #     steps:
+  #     - uses: lwhiteley/dependent-jobs-result-check@v1
+  #       id: check_statuses
+  #       with:
+  #         statuses: failure
+  #         dependencies: ${{toJSON(needs) }}
+  #     - name: Log output
+  #       run: |
+  #         echo "statuses:" "${{ steps.check_statuses.outputs.statuses }}"
+  #         echo "jobs:" "${{ steps.check_statuses.outputs.jobs }}"
+  #         echo "found any?:" "${{ steps.check_statuses.outputs.found }}"
     
-      - name: Cancel if failure
-        if: ${{ steps.check_statuses.outputs.found == 'true' }}
-        run: |
-          exit 1
+  #     - name: Cancel if failure
+  #       if: ${{ steps.check_statuses.outputs.found == 'true' }}
+  #       run: |
+  #         exit 1
 
   FastBuild:
     name: Fast builds
