TEST add PrintModifiedFiles

diff --git a/.github/workflows/pr_push.yml b/.github/workflows/pr_push.yml
--- a/.github/workflows/pr_push.yml
+++ b/.github/workflows/pr_push.yml
@@ -39,7 +39,6 @@ jobs:
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
-          exit 1
           echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
 
   BuildCIContainer:
@@ -48,35 +47,33 @@ jobs:
     secrets: inherit
     uses: ./.github/workflows/build_ci_container.yml
 
-  CheckStatus:
-      runs-on: ubuntu-latest
-      outputs:
-        check_status: ${{ steps.check_statuses.outputs.found }}
-      name: Check Status
-      # needs: [CodeChecks, DocsBuild, BuildCIContainer]
-      needs: [CodeChecks]
-      if: always()
-      steps:
-      - uses: lwhiteley/dependent-jobs-result-check@v1
-        id: check_statuses
-        with:
-          statuses: failure
-          dependencies: ${{toJSON(needs) }}
-      - name: Log output
-        run: |
-          echo "statuses:" "${{ steps.check_statuses.outputs.statuses }}"
-          echo "jobs:" "${{ steps.check_statuses.outputs.jobs }}"
-          echo "found any?:" "${{ steps.check_statuses.outputs.found }}"
+  # CheckStatus:
+  #     runs-on: ubuntu-latest
+  #     outputs:
+  #       check_status: ${{ steps.check_statuses.outputs.found }}
+  #     name: Check Status
+  #     needs: [CodeChecks, DocsBuild, BuildCIContainer]
+  #     if: always()
+  #     steps:
+  #     - uses: lwhiteley/dependent-jobs-result-check@v1
+  #       id: check_statuses
+  #       with:
+  #         statuses: failure
+  #         dependencies: ${{toJSON(needs) }}
+  #     - name: Log output
+  #       run: |
+  #         echo "statuses:" "${{ steps.check_statuses.outputs.statuses }}"
+  #         echo "jobs:" "${{ steps.check_statuses.outputs.jobs }}"
+  #         echo "found any?:" "${{ steps.check_statuses.outputs.found }}"
     
-      - name: Cancel if failure
-        if: ${{ steps.check_statuses.outputs.found == 'true' }}
-        run: |
-          exit 1
+  #     - name: Cancel if failure
+  #       if: ${{ steps.check_statuses.outputs.found == 'true' }}
+  #       run: |
+  #         exit 1
 
   FastBuild:
     name: Fast builds
-    # needs: [CheckStatus, CodeChecks, DocsBuild]
-    needs: [CheckStatus]
+    needs: [DocsBuild, BuildCIContainer]
     uses: ./.github/workflows/reusable_fast.yml
   # Nightly:
   #   uses: ./.github/workflows/nightly.yml
